package com.yaps.petstore.domain.constant;

/**
 * This class lists all the countries.
 */
public class Countries {

    // ======================================
    // =             Attributes             =
    // ======================================
    private static final String[] _all = {
        ""
        , "Andorra, Principality of"
        , "United Arab Emirates"
        , "Antigua and Barbuda"
        , "Anguilla"
        , "Albania"
        , "Armenia"
        , "Netherlands Antilles"
        , "Angola"
        , "Antarctica"
        , "Argentina"
        , "American Samoa"
        , "Austria"
        , "Australia"
        , "Aruba"
        , "Azerbaidjan"
        , "Bosnia - Herzegovina"
        , "Barbados"
        , "Bangladesh"
        , "Belgium"
        , "Burkina Faso"
        , "Bulgaria"
        , "Bahrain"
        , "Burundi"
        , "Benin"
        , "Bermuda"
        , "Brunei Darussalam"
        , "Bolivia"
        , "Brazil"
        , "Bahamas"
        , "Bhutan"
        , "Bouvet Island"
        , "Botswana"
        , "Belarus"
        , "Belize"
        , "Cocos(Keeling) Islands"
        , "Congo, The Democratic Republic of the"
        , "Central African Republic"
        , "Congo"
        , "Switzerland"
        , "Ivory Coast(Cote D'Ivoire)"
        , "Cook Islands"
        , "Chile"
        , "Cameroon"
        , "China"
        , "Colombia"
        , "Costa Rica"
        , "Former Czechoslovakia"
        , "Cape Verde"
        , "Christmas Island"
        , "Cyprus"
        , "Czech Republic"
        , "Germany"
        , "Djibouti"
        , "Denmark"
        , "Dominica"
        , "Dominican Republic"
        , "Algeria"
        , "Ecuador"
        , "Estonia"
        , "Egypt"
        , "Western Sahara"
        , "Eritrea"
        , "Spain"
        , "Ethiopia"
        , "Finland"
        , "Fiji"
        , "Falkland Islands"
        , "Micronesia"
        , "Faroe Islands"
        , "France"
        , "Gabon"
        , "Great Britain"
        , "Grenada"
        , "Georgia"
        , "French Guyana"
        , "Ghana"
        , "Gibraltar"
        , "Greenland"
        , "Gambia"
        , "Guinea"
        , "Guadeloupe(French)"
        , "Equatorial Guinea"
        , "Greece"
        , "Guatemala"
        , "Guam(USA)"
        , "Guinea Bissau"
        , "Guyana"
        , "Hong Kong"
        , "Heard and McDonald Islands"
        , "Honduras"
        , "Croatia"
        , "Haiti"
        , "Hungary"
        , "Indonesia"
        , "Ireland"
        , "Israel"
        , "British Indian Ocean Territory"
        , "Iceland"
        , "Italy"
        , "Jamaica"
        , "Jordan"
        , "Japan"
        , "Kenya"
        , "Kyrgyz Republic(Kyrgyzstan)"
        , "Cambodia, Kingdom of"
        , "Kiribati"
        , "Comoros"
        , "Saint Kitts & Nevis Anguilla"
        , "South Korea"
        , "Kuwait"
        , "Cayman Islands"
        , "Kazakhstan"
        , "Laos"
        , "Lebanon"
        , "Saint Lucia"
        , "Liechtenstein"
        , "Sri Lanka"
        , "Liberia"
        , "Lesotho"
        , "Lithuania"
        , "Luxembourg"
        , "Latvia"
        , "Morocco"
        , "Monaco"
        , "Moldavia"
        , "Madagascar"
        , "Marshall Islands"
        , "Macedonia"
        , "Mali"
        , "Myanmar"
        , "Mongolia"
        , "Macau"
        , "Northern Mariana Islands"
        , "Martinique(French)"
        , "Mauritania"
        , "Montserrat"
        , "Malta"
        , "Mauritius"
        , "Maldives"
        , "Malawi"
        , "Mexico"
        , "Malaysia"
        , "Mozambique"
        , "Namibia"
        , "New Caledonia(French)"
        , "Niger"
        , "Norfolk Island"
        , "Nigeria"
        , "Nicaragua"
        , "Netherlands"
        , "Norway"
        , "Nepal"
        , "Nauru"
        , "Neutral Zone"
        , "Niue"
        , "New Zealand"
        , "Oman"
        , "Panama"
        , "Peru"
        , "Polynesia(French)"
        , "Papua New Guinea"
        , "Philippines"
        , "Pakistan"
        , "Poland"
        , "Saint Pierre and Miquelon"
        , "Pitcairn Island"
        , "Puerto Rico"
        , "Portugal"
        , "Palau"
        , "Paraguay"
        , "Qatar"
        , "Reunion(French)"
        , "Romania"
        , "Russian Federation"
        , "Rwanda"
        , "Saudi Arabia"
        , "Solomon Islands"
        , "Seychelles"
        , "Sweden"
        , "Singapore"
        , "Saint Helena"
        , "Slovenia"
        , "Svalbard and Jan Mayen Islands"
        , "Slovak Republic"
        , "Sierra Leone"
        , "San Marino"
        , "Senegal"
        , "Somalia"
        , "Suriname"
        , "Saint Tome(Sao Tome) and Principe"
        , "Former USSR"
        , "El Salvador"
        , "Swaziland"
        , "Turks and Caicos Islands"
        , "Chad"
        , "French Southern Territories"
        , "Togo"
        , "Thailand"
        , "Tadjikistan"
        , "Tokelau"
        , "Turkmenistan"
        , "Tunisia"
        , "Tonga"
        , "East Timor"
        , "Turkey"
        , "Trinidad and Tobago"
        , "Tuvalu"
        , "Taiwan"
        , "Tanzania"
        , "Ukraine"
        , "Uganda"
        , "United Kingdom"
        , "USA"
        , "USA Minor Outlying Islands"
        , "Uruguay"
        , "Uzbekistan"
        , "Holy See(Vatican City State)"
        , "Saint Vincent & Grenadines"
        , "Venezuela"
        , "Virgin Islands(British)"
        , "Virgin Islands(USA)"
        , "Vietnam"
        , "Vanuatu"
        , "Wallis and Futuna Islands"
        , "Samoa"
        , "Yemen"
        , "Mayotte"
        , "Serbia & Montenegro(Yugoslavia)"
        , "South Africa"
        , "Zambia"
        , "Zaire"
        , "Zimbabwe"
    };

    // ======================================
    // =         Getters and Setters        =
    // ======================================
    public static String[] getAll() {
        return _all;
    }
}